### ISSUE TITLE
consider using in glob-fs

### ISSUE THREAD

**Issue by jonschlinkert** [micromatch/bash-glob#1]
I still don't know how well this will perform cross-platform. Once we get appveyor hooked up and more coverage we can review

**Comment by ghost** [comment]
@jonschlinkert This isn't working on the Windows plattform at all. Any ideas how I can get it to work? Only Windows 10 have a option to install Ubuntu sub-system.
Windows 8 and older this doesn't work.
Only way to get this working is on Windows 10 with git software.  Ideas??

**Comment by ghost** [comment]
@jonschlinkert Here are a few errors that I get. How to fix this?

``` js

 1) files event should not return duplicate matches:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at Function.<anonymous> (test\events.files.js:31:7)
      at Function.Emitter.emit (node_modules\component-emitter\index.js:133:20)
      at Function.glob.end (index.js:213:8)
      at Function.glob.sync (index.js:204:8)
      at index.js:156:29
      at Array.reduce (native)
      at Function.glob.sync (index.js:155:20)
      at Context.<anonymous> (test\events.files.js:34:10)

  2) match event should not return duplicate matches:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

 3) options.cwd cwd globbing no matches:

      Uncaught AssertionError: should have same files of matches
      + expected - actual

       [
         "\u0000"
      -  "\u0000\r\u0000\r\u0000"
         "\u0000P\u0000r\u0000e\u0000s\u0000s\u0000 \u0000a\u0000n\u0000y\u0000 \u0000k\u0000e\u0000y\u0000 \u0000t\u0000o\u0000 \u0000c\u0000o\u0000n\u0000t\u0000i\u0000n\u0000u\u0000e\u0000.\u0000.\u0000.\u0000\r\u0000\r\u0000"
      -  "\u0000T\u0000h\u0000e\u0000 \u0000L\u0000X\u0000 \u0000s\u0000u\u0000b\u0000s\u0000y\u0000s\u0000t\u0000e\u0000m\u0000 \u0000h\u0000a\u0000s\u0000 \u0000a\u0000n\u0000 \u0000i\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000,\u0000 \u0000u\u0000n\u0000i\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000,\u0000 \u0000o\u0000r\u0000 \u0000s\u0000e\u0000r\u0000v\u0000i\u0000c\u0000i\u0000n\u0000g\u0000 \u0000o\u0000p\u0000e\u0000r\u0000a\u0000t\u0000i\u0000o\u0000n\u0000 \u0000p\u0000e\u0000n\u0000d\u0000i\u0000n\u0000g\u0000.\u0000\r\u0000\r\u0000"
      -  "\u0000T\u0000h\u0000i\u0000s\u0000 \u0000w\u0000i\u0000l\u0000l\u0000 \u0000i\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000 \u0000U\u0000b\u0000u\u0000n\u0000t\u0000u\u0000 \u0000o\u0000n\u0000 \u0000W\u0000i\u0000n\u0000d\u0000o\u0000w\u0000s\u0000,\u0000 \u0000d\u0000i\u0000s\u0000t\u0000r\u0000i\u0000b\u0000u\u0000t\u0000e\u0000d\u0000 \u0000b\u0000y\u0000 \u0000C\u0000a\u0000n\u0000o\u0000n\u0000i\u0000c\u0000a\u0000l\u0000\r\u0000\r\u0000"
      -  "\u0000a\u0000n\u0000d\u0000 \u0000l\u0000i\u0000c\u0000e\u0000n\u0000s\u0000e\u0000d\u0000 \u0000u\u0000n\u0000d\u0000e\u0000r\u0000 \u0000i\u0000t\u0000s\u0000 \u0000t\u0000e\u0000r\u0000m\u0000s\u0000 \u0000a\u0000v\u0000a\u0000i\u0000l\u0000a\u0000b\u0000l\u0000e\u0000 \u0000h\u0000e\u0000r\u0000e\u0000:\u0000 \u0000\r\u0000\r\u0000"
      -  "\u0000h\u0000t\u0000t\u0000p\u0000s\u0000:\u0000/\u0000/\u0000a\u0000k\u0000a\u0000.\u0000m\u0000s\u0000/\u0000u\u0000o\u0000w\u0000t\u0000e\u0000r\u0000m\u0000s\u0000\r\u0000\r\u0000"
      -  "-\u0000-\u0000 \u0000B\u0000e\u0000t\u0000a\u0000 \u0000f\u0000e\u0000a\u0000t\u0000u\u0000r\u0000e\u0000 \u0000-\u0000-\u0000 \u0000\r\u0000\r\u0000"
         "C\u0000a\u0000n\u0000n\u0000o\u0000t\u0000 \u0000l\u0000a\u0000u\u0000n\u0000c\u0000h\u0000 \u0000b\u0000a\u0000s\u0000h\u0000 \u0000b\u0000e\u0000c\u0000a\u0000u\u0000s\u0000e\u0000 \u0000t\u0000h\u0000e\u0000 \u0000L\u0000X\u0000 \u0000s\u0000u\u0000b\u0000s\u0000y\u0000s\u0000t\u0000e\u0000m\u0000 \u0000h\u0000a\u0000s\u0000 \u0000a\u0000n\u0000 \u0000i\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000,\u0000 \u0000u\u0000n\u0000i\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000,\u0000 \u0000o\u0000r\u0000 \u0000s\u0000e\u0000r\u0000v\u0000i\u0000c\u0000i\u0000n\u0000g\u0000 \u0000o\u0000p\u0000e\u0000r\u0000a\u0000t\u0000i\u0000o\u0000n\u0000 \u0000p\u0000e\u0000n\u0000d\u0000i\u0000n\u0000g\u0000.\u0000\r\u0000\r\u0000"
      -  "P\u0000r\u0000e\u0000s\u0000s\u0000 \u0000a\u0000n\u0000y\u0000 \u0000k\u0000e\u0000y\u0000 \u0000t\u0000o\u0000 \u0000c\u0000o\u0000n\u0000t\u0000i\u0000n\u0000u\u0000e\u0000.\u0000.\u0000.\u0000\r\u0000\r\u0000"
       ]

      at Function.<anonymous> (test\events.match.js:32:14)
      at Function.on (node_modules\component-emitter\index.js:65:8)
      at Function.Emitter.emit (node_modules\component-emitter\index.js:133:20)
      at Function.glob.end (index.js:213:8)
      at index.js:68:26
      at ChildProcess.<anonymous> (index.js:252:7)
      at ChildProcess.cp.emit (node_modules\cross-spawn\lib\enoent.js:40:29)
      at maybeClose (internal/child_process.js:877:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)


 11) options.nonull a/*NOFILE*/**/ { nonull: true }:

      AssertionError: sync results
      + expected - actual

       [
      -  "\u0000"
      -  "\u0000P\u0000r\u0000e\u0000s\u0000s\u0000 \u0000a\u0000n\u0000y\u0000 \u0000k\u0000e\u0000y\u0000 \u0000t\u0000o\u0000 \u0000c\u0000o\u0000n\u0000t\u0000i\u0000n\u0000u\u0000e\u0000.\u0000.\u0000.\u0000\r\u0000\r\u0000"
      -  "C\u0000a\u0000n\u0000n\u0000o\u0000t\u0000 \u0000l\u0000a\u0000u\u0000n\u0000c\u0000h\u0000 \u0000b\u0000a\u0000s\u0000h\u0000 \u0000b\u0000e\u0000c\u0000a\u0000u\u0000s\u0000e\u0000 \u0000t\u0000h\u0000e\u0000 \u0000L\u0000X\u0000 \u0000s\u0000u\u0000b\u0000s\u0000y\u0000s\u0000t\u0000e\u0000m\u0000 \u0000h\u0000a\u0000s\u0000 \u0000a\u0000n\u0000 \u0000i\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000,\u0000 \u0000u\u0000n\u0000i\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000,\u0000 \u0000o\u0000r\u0000 \u0000s\u0000e\u0000r\u0000v\u0000i\u0000c\u0000i\u0000n\u0000g\u0000 \u0000o\u0000p\u0000e\u0000r\u0000a\u0000t\u0000i\u0000o\u0000n\u0000 \u0000p\u0000e\u0000n\u0000d\u0000i\u0000n\u0000g\u0000.\u0000\r\u0000\r\u0000"
      +  "a/*NOFILE*/**/"
       ]

      at Context.<anonymous> (test\options.nonull.js:36:14)
```

**Comment by jonschlinkert** [comment]
> Only way to get this working is on Windows 10 with git software.

You don't need git, you need `bash` installed. I don't know how to get that running on older windows

**Comment by ghost** [comment]
I know you would need to install bash, and home I can do that, but not on the company computers. So I will just keep an eye on this repo and see if there will be an fix in the future.

**Comment by jonschlinkert** [comment]
> So I will just keep an eye on this repo and see if there will be an fix in the future.

we're working on it now, @doowb setup a virtual windows box and is helping me look into solutions. we'll keep you posted

**Comment by wabblerjs** [comment]
@jonschlinkert @doowb Any progress on this one? 

I have now more or less tested all of your modules in your Github repo, and mostly everyone seems to file on Windows. And I also saw that others have reported the same - glob-fs - to mention one.

And things haven't been fixed even after 10 months?????????

I say 10 months because back in december 2015 you - @jonschlinkert  - said you should solve one issue found on glob.fs.

Why thos??

**Comment by jonschlinkert** [comment]
@wabblerjs I deleted your comment because it was extremely rude (and factually incorrect). I have 1,200 modules that have been downloaded 5 billion times in the past 2 years. Go contribute something to the community yourself and stop acting like you're entitled to my time or my contributions. I don't own you anything. Moreover, I used Windows for 20 years, and only recently switched to mac. I know for a fact that most of my modules work just fine on windows, only this module (which uses bash) and **the unit tests ONLY** for other very recently published modules use bash, which obviously will fail on windows. I used bash to test for parity, but it doesn't mean the modules themselves don't work on windows. Does that make sense to you? I'm not really interested in your reply, thus I've blocked you. Please go bother someone else.
